//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyPrinterz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocID { get; set; }
        public string DocName { get; set; }
        public string DocType { get; set; }
        public byte[] DocUrl { get; set; }
        public Nullable<int> EngenPrintersID { get; set; }
    
        public virtual Printer Printer { get; set; }
    }
}
